services:
  # Backend API service
  - type: web
    name: retinopathy-api
    env: python
    plan: free
    buildCommand: |
      pip install --upgrade pip
      pip install tensorflow-io-gcs-filesystem==0.31.0
      pip install tensorflow==2.14.0 --no-deps
      pip install -r requirements.txt
    startCommand: gunicorn app:app --log-level debug --timeout 300 --workers 1 --threads 2 --max-requests 2 --max-requests-jitter 1 --access-logfile - --error-logfile -
    autoDeploy: true
    # Konfigurasi untuk model berukuran besar
    disk:
      name: model-storage
      mountPath: /opt/render/project/src
      sizeGB: 3
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.16
      - key: TF_CPP_MIN_LOG_LEVEL
        value: 1
      - key: TF_FORCE_GPU_ALLOW_GROWTH
        value: true
      - key: PYTHONUNBUFFERED
        value: true
      - key: PORT
        value: 10000
    buildpacks:
      - url: https://github.com/heroku/heroku-buildpack-apt 